[package]
name = "extract_nested_eml"
version = "0.1.0"
authors = ["horle <horle@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mailparse = "0.13.7"
regex = "1.5.4"
